select * from SPRINGUSERS;
select * from SPRINGBOARD;

SELECT * FROM 
(SELECT ROWNUM AS RNUM,B.* FROM
(SELECT SEQ,TITLE,WRITER,CONTENT,TO_CHAR(REGDATE,'YYYY-MM-DD HH:MI:SS')AS REGDATE,CNT FROM SPRINGBOARD ORDER BY SEQ DESC) B) 
WHERE RNUM BETWEEN 1 AND 10 ORDER BY SEQ DESC;

select * 
from ALL_TAB_COLUMNS
where TABLE_NAME = 'SPRINGBOARD';

SELECT * FROM (SELECT ROWNUM AS RNUM,B.* FROM 
(SELECT SEQ,TITLE,WRITER,CONTENT,TO_CHAR(REGDATE,'YYYY-MM-DD HH:MI:SS') AS REGDATE,CNT FROM SPRINGBOARD 
WHERE ${searchCondition} LIKE '%'||#{searchKeyword}||'%' ORDER BY SEQ DESC) B) 
WHERE RNUM BETWEEN #{page}*10-9 AND #{page}*10

select * from springboard;




SELECT * FROM (SELECT ROWNUM AS RNUM,B.* FROM (SELECT SEQ,TITLE,WRITER,CONTENT,TO_CHAR(REGDATE,'YYYY-MM-DD HH:MI:SS') AS REGDATE,CNT FROM SPRINGBOARD WHERE TITLE LIKE '%제목%' ORDER BY SEQ DESC) B) WHERE RNUM BETWEEN 1 AND 10

